"""Technician role

Revision ID: 87dd43829e3c
Revises: 83cdbdb8f14d
Create Date: 2025-03-04 10:16:07.450907

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87dd43829e3c'
down_revision: Union[str, None] = '83cdbdb8f14d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technician_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technician_roles_id'), 'technician_roles', ['id'], unique=False)
    op.create_index(op.f('ix_technician_roles_name'), 'technician_roles', ['name'], unique=True)
    op.add_column('technicians', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'technicians', 'technician_roles', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'technicians', type_='foreignkey')
    op.drop_column('technicians', 'role_id')
    op.drop_index(op.f('ix_technician_roles_name'), table_name='technician_roles')
    op.drop_index(op.f('ix_technician_roles_id'), table_name='technician_roles')
    op.drop_table('technician_roles')
    # ### end Alembic commands ###
